use argon2::{
    Argon2, PasswordHasher,
    password_hash::{SaltString, rand_core::OsRng},
};

fn validate_password_strength(s: &str) -> bool {
    if s.len() < 8 {
        return false;
    }
    let estimate = zxcvbn::zxcvbn(s, &[]);
    estimate.score() >= zxcvbn::Score::Two
}

#[nutype::nutype(
    validate(predicate = validate_password_strength),
    derive(Debug, Deserialize),
    // Intentionally NOT Serialize or Clone because passwords must never appear in
    // response bodies and should not be copied around freely.
)]
pub struct PlainPassword(zeroize::Zeroizing<String>);

/*
into_inner function generated by nutype macro:

impl PlainPassword {
    #[inline]
    pub fn into_inner(self) -> zeroize::Zeroizing<String> {
        self.0
    }
}
*/

pub struct HashedPassword(String);

impl HashedPassword {
    pub fn as_str(&self) -> &str {
        &self.0.as_ref()
    }
}

impl PlainPassword {
    /// Converts self into a secure hashed password.
    /// Drops self. (deallocates)
    pub fn hash(self) -> HashedPassword {
        // move the Zeroizing<String> out of self to ensure
        // the plaintext password is explicitly owned only here
        let zeroizing = self.into_inner();

        let hash = {
            // borrow as &str to avoid any copies of sensitive data
            let password = zeroizing.as_str();

            // generate a secure random hash for each password
            // to protect against rainbow table attacks
            let salt = SaltString::generate(&mut OsRng);

            // argon2 industry standard i think
            Argon2::default()
                .hash_password(password.as_bytes(), &salt)
                .expect("passsword hashing failed")
                .to_string()
        };

        // explicitly drop the Zeroizing wrapper
        // this will zero the underlying buffer,
        // ensuring the plaintext no longer exists
        drop(zeroizing);

        HashedPassword(hash)
    }
}
